image: openjdk:22

pipelines:
  default:
    - step:
        name: Install Maven and Build
        caches:
          - maven
        script:
          - apt-get update && apt-get install -y maven
          - mvn -version  # Optional: Check Maven version
          - mvn clean install
    - step:
        name: Package Application
        caches:
          - maven
        script:
          - mvn clean package -DskipTests

definitions:
  caches:
    maven: ~/.m2/repository
