image: maven:3.8.8

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn -B verify --file pom.xml
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0

        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1

    - step:
        name: Deploy to VPS
        deployment: production  # Optional: Set this to your desired deployment environment
        script:
          - echo "Starting build and deployment..."
          
          # Build the project
          - mvn clean install

          # Define variables
          - SSH_HOST="103.168.18.176"
          - SSH_USER="root"
          - REMOTE_DIR="/System/projects/java/chavdar_vishranti/jars"

          # Find the JAR file dynamically in the target directory
          - JAR_FILE=$(find target -name "*.jar" | head -n 1)

          # Create SSH key file
          - mkdir -p ~/.ssh
          - echo "$SSH_KEY" > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa

          # Copy JAR file to VPS
          - echo "Copying JAR file to VPS..."
          - scp -o StrictHostKeyChecking=no $JAR_FILE $SSH_USER@$SSH_HOST:$REMOTE_DIR

          # Run the JAR on the VPS
          - echo "Starting Eureka Server on VPS..."
          - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "nohup java -jar $REMOTE_DIR/$(basename $JAR_FILE) > /dev/null 2>&1 &"
