image: maven:3.8.7-openjdk-22

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install
    - step:
        name: Package Application
        caches:
          - maven
        script:
          - mvn clean package -DskipTests

definitions:
  caches:
    maven: ~/.m2/repository
