name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known_hosts
      run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      env:
        SSH_HOST: "103.168.18.176"

    - name: Create SSH Key File
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy JAR to VPS
      run: scp -r target/*.jar $SSH_USER@$SSH_HOST:$REMOTE_DIR/
      env:
        SSH_HOST: "103.168.18.176"
        SSH_USER: "root"
        REMOTE_DIR: "/system/projects/java/chavdar_vishranti/jars/eureka-server"
        
    - name: Debug SSH Key
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa

    # - name: Stop existing service on VPS
    #   run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -vvv $SSH_USER@$SSH_HOST "pkill -f 'eureka-server-0.0.1-SNAPSHOT.jar' || true"
    #   env:
    #     SSH_HOST: "103.168.18.176"
    #     SSH_USER: "root"
    
    - name: Stop existing service on VPS
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "pkill -f 'eureka-server-0.0.1-SNAPSHOT.jar' || true"
      env:
        SSH_HOST: "103.168.18.176"
        SSH_USER: "root" 
    # - name: Stop existing service on VPS
    #   run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "pkill -f 'eureka-server-0.0.1-SNAPSHOT.jar' || true"
    #   env:
    #     SSH_HOST: "103.168.18.176"
    #     SSH_USER: "root"

    - name: Start new service on VPS
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "nohup java -jar $REMOTE_DIR/eureka-server-0.0.1-SNAPSHOT.jar > $REMOTE_DIR/eureka-server.log 2>&1 &"
      env:
        SSH_HOST: "103.168.18.176"
        SSH_USER: "root"
        REMOTE_DIR: "/system/projects/java/chavdar_vishranti/jars/eureka-server"
