name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known_hosts
      run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      env:
        SSH_HOST: "103.168.18.176"

    - name: Deploy to VPS
      run: |
        scp -r target/*.jar $SSH_USER@$SSH_HOST:$REMOTE_DIR/
        ssh $SSH_USER@$SSH_HOST << EOF
          pkill -f 'eureka-server'
          nohup java -jar $REMOTE_DIR/eureka-server.jar > /dev/null 2>&1 &
        EOF
      env:
        SSH_HOST: "103.168.18.176"  # VPS IP address
        SSH_USER: "root"            # SSH user
        REMOTE_DIR: "/system/projects/java/chavdar_vishranti/jars/eureka-server"
